### ISSUE TITLE
good fucking source

### ISSUE THREAD

**Issue by Exotikcheatt** [SoarCheats/DummyDrv-Recode#1]
good source but only detection problem into driver ban assured + TOPMOST OVERLAY
**KeStackAttachProcess**
**KeUnstackDetachProcess**

```
const UINT64 GetProcessCr3(const PEPROCESS pProcess)
{
	KAPC_STATE State = { 0 };
	KeStackAttachProcess(pProcess, &State);
	auto Cr3 = __readcr3();
	KeUnstackDetachProcess**(&State); 
	return Cr3;
}
```

**Comment by SoarCheats** [comment]
any attach process would not be automatically detected, if you would re-read the windows nt function list you will see that this function is used buy over 300 differnet vuln drivers and windows drivers for calls to NtUser and such, but yes the topmost overlay and attach process functions will indeed throw a flag but not enough to cause an instant ban or even a 1 day ban, will take more flags from um or km such as the intristic __readcr3(), which is calling straight from the cr3 and storing it in rax.
